// <auto-generated />
using System;
using BiblioNET.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BiblioNET.Api.Migrations
{
    [DbContext(typeof(BiblioNetDbContext))]
    partial class BiblioNetDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BiblioNET.Api.Domain.Genero", b =>
                {
                    b.Property<int>("GeneroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GeneroId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("GeneroId");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Generos", (string)null);

                    b.HasData(
                        new
                        {
                            GeneroId = 1,
                            Activo = true,
                            Descripcion = "Obras narrativas de ficción",
                            FechaRegistro = new DateTime(2026, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Novela"
                        },
                        new
                        {
                            GeneroId = 2,
                            Activo = true,
                            Descripcion = "Programación, arquitectura y tecnología",
                            FechaRegistro = new DateTime(2026, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Tecnología"
                        },
                        new
                        {
                            GeneroId = 3,
                            Activo = true,
                            Descripcion = "Historia universal y regional",
                            FechaRegistro = new DateTime(2026, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Historia"
                        },
                        new
                        {
                            GeneroId = 4,
                            Activo = true,
                            Descripcion = "Divulgación y ciencias aplicadas",
                            FechaRegistro = new DateTime(2026, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Ciencia"
                        });
                });

            modelBuilder.Entity("BiblioNET.Api.Domain.Lector", b =>
                {
                    b.Property<int>("LectorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LectorId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("LectorId");

                    b.HasIndex("Documento")
                        .IsUnique();

                    b.ToTable("Lectores", (string)null);

                    b.HasData(
                        new
                        {
                            LectorId = 1,
                            Activo = true,
                            Apellidos = "Torres",
                            Documento = "74000001",
                            Email = "ana.torres@example.com",
                            FechaRegistro = new DateTime(2026, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Ana"
                        },
                        new
                        {
                            LectorId = 2,
                            Activo = true,
                            Apellidos = "Ramírez",
                            Documento = "74000002",
                            Email = "luis.ramirez@example.com",
                            FechaRegistro = new DateTime(2026, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Luis"
                        });
                });

            modelBuilder.Entity("BiblioNET.Api.Domain.Libro", b =>
                {
                    b.Property<int>("LibroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LibroId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("GeneroId")
                        .HasColumnType("int");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("LibroId");

                    b.HasIndex("GeneroId");

                    b.HasIndex("ISBN")
                        .IsUnique();

                    b.HasIndex("Stock");

                    b.HasIndex("Titulo");

                    b.ToTable("Libros", null, t =>
                        {
                            t.HasCheckConstraint("CK_Libros_Stock", "[Stock] >= 0");
                        });

                    b.HasData(
                        new
                        {
                            LibroId = 1,
                            Activo = true,
                            Autor = "Gabriel García Márquez",
                            FechaRegistro = new DateTime(2026, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GeneroId = 1,
                            ISBN = "9780307474728",
                            Stock = 4,
                            Titulo = "Cien años de soledad"
                        },
                        new
                        {
                            LibroId = 2,
                            Activo = true,
                            Autor = "Robert C. Martin",
                            FechaRegistro = new DateTime(2026, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GeneroId = 2,
                            ISBN = "9780132350884",
                            Stock = 3,
                            Titulo = "Clean Code"
                        },
                        new
                        {
                            LibroId = 3,
                            Activo = true,
                            Autor = "Martin Kleppmann",
                            FechaRegistro = new DateTime(2026, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GeneroId = 2,
                            ISBN = "9781449373320",
                            Stock = 2,
                            Titulo = "Designing Data-Intensive Applications"
                        },
                        new
                        {
                            LibroId = 4,
                            Activo = true,
                            Autor = "Yuval Noah Harari",
                            FechaRegistro = new DateTime(2026, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GeneroId = 3,
                            ISBN = "9780062316097",
                            Stock = 5,
                            Titulo = "Sapiens"
                        },
                        new
                        {
                            LibroId = 5,
                            Activo = true,
                            Autor = "Stephen Hawking",
                            FechaRegistro = new DateTime(2026, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GeneroId = 4,
                            ISBN = "9780553380163",
                            Stock = 1,
                            Titulo = "A Brief History of Time"
                        });
                });

            modelBuilder.Entity("BiblioNET.Api.Domain.LibroBenchmarkConIndice", b =>
                {
                    b.Property<int>("LibroBenchmarkConIndiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LibroBenchmarkConIndiceId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("GeneroId")
                        .HasColumnType("int");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("LibroBenchmarkConIndiceId");

                    b.HasIndex("GeneroId", "Stock", "Activo")
                        .HasDatabaseName("IX_LibrosBenchmarkConIndice_GeneroId_Stock_Activo");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("GeneroId", "Stock", "Activo"), new[] { "Titulo", "Autor", "ISBN" });

                    b.ToTable("LibrosBenchmarkConIndice", (string)null);
                });

            modelBuilder.Entity("BiblioNET.Api.Domain.LibroBenchmarkSinIndice", b =>
                {
                    b.Property<int>("LibroBenchmarkSinIndiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LibroBenchmarkSinIndiceId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("GeneroId")
                        .HasColumnType("int");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("LibroBenchmarkSinIndiceId");

                    b.ToTable("LibrosBenchmarkSinIndice", (string)null);
                });

            modelBuilder.Entity("BiblioNET.Api.Domain.Prestamo", b =>
                {
                    b.Property<int>("PrestamoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PrestamoId"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<DateTime>("FechaPrestamo")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("datetime2");

                    b.Property<int>("LectorId")
                        .HasColumnType("int");

                    b.HasKey("PrestamoId");

                    b.HasIndex("LectorId", "FechaPrestamo");

                    b.ToTable("Prestamos", null, t =>
                        {
                            t.HasCheckConstraint("CK_Prestamos_Estado", "[Estado] IN ('ACTIVO','DEVUELTO','VENCIDO')");

                            t.HasCheckConstraint("CK_Prestamos_Fechas", "[FechaVencimiento] >= [FechaPrestamo]");
                        });
                });

            modelBuilder.Entity("BiblioNET.Api.Domain.PrestamoDetalle", b =>
                {
                    b.Property<int>("PrestamoDetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PrestamoDetalleId"));

                    b.Property<short>("Cantidad")
                        .HasColumnType("smallint");

                    b.Property<bool>("Devuelto")
                        .HasColumnType("bit");

                    b.Property<int>("LibroId")
                        .HasColumnType("int");

                    b.Property<int>("PrestamoId")
                        .HasColumnType("int");

                    b.HasKey("PrestamoDetalleId");

                    b.HasIndex("LibroId");

                    b.HasIndex("PrestamoId", "LibroId")
                        .IsUnique();

                    b.ToTable("PrestamoDetalle", null, t =>
                        {
                            t.HasCheckConstraint("CK_PrestamoDetalle_Cantidad", "[Cantidad] > 0");
                        });
                });

            modelBuilder.Entity("BiblioNET.Api.Domain.Libro", b =>
                {
                    b.HasOne("BiblioNET.Api.Domain.Genero", "Genero")
                        .WithMany("Libros")
                        .HasForeignKey("GeneroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Genero");
                });

            modelBuilder.Entity("BiblioNET.Api.Domain.Prestamo", b =>
                {
                    b.HasOne("BiblioNET.Api.Domain.Lector", "Lector")
                        .WithMany("Prestamos")
                        .HasForeignKey("LectorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Lector");
                });

            modelBuilder.Entity("BiblioNET.Api.Domain.PrestamoDetalle", b =>
                {
                    b.HasOne("BiblioNET.Api.Domain.Libro", "Libro")
                        .WithMany("PrestamoDetalles")
                        .HasForeignKey("LibroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BiblioNET.Api.Domain.Prestamo", "Prestamo")
                        .WithMany("Detalles")
                        .HasForeignKey("PrestamoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Libro");

                    b.Navigation("Prestamo");
                });

            modelBuilder.Entity("BiblioNET.Api.Domain.Genero", b =>
                {
                    b.Navigation("Libros");
                });

            modelBuilder.Entity("BiblioNET.Api.Domain.Lector", b =>
                {
                    b.Navigation("Prestamos");
                });

            modelBuilder.Entity("BiblioNET.Api.Domain.Libro", b =>
                {
                    b.Navigation("PrestamoDetalles");
                });

            modelBuilder.Entity("BiblioNET.Api.Domain.Prestamo", b =>
                {
                    b.Navigation("Detalles");
                });
#pragma warning restore 612, 618
        }
    }
}
