/*
 * DemoApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Net.Http;
using Microsoft.Extensions.DependencyInjection;
using MiClienteReservas.Api;
using MiClienteReservas.Model;

namespace MiClienteReservas.Client
{
    /// <summary>
    /// Provides hosting configuration for MiClienteReservas
    /// </summary>
    public partial class HostConfiguration
    {
        private readonly IServiceCollection _services;
        private readonly JsonSerializerOptions _jsonOptions = new JsonSerializerOptions();

        internal bool HttpClientsAdded { get; private set; }

        /// <summary>
        /// Instantiates the class 
        /// </summary>
        /// <param name="services"></param>
        public HostConfiguration(IServiceCollection services)
        {
            _services = services;
            _jsonOptions.Converters.Add(new JsonStringEnumConverter());
            _jsonOptions.Converters.Add(new DateTimeJsonConverter());
            _jsonOptions.Converters.Add(new DateTimeNullableJsonConverter());
            _jsonOptions.Converters.Add(new DateOnlyJsonConverter());
            _jsonOptions.Converters.Add(new DateOnlyNullableJsonConverter());
            _jsonOptions.Converters.Add(new CategoryJsonConverter());
            _jsonOptions.Converters.Add(new CategoryApiResponseJsonConverter());
            _jsonOptions.Converters.Add(new CategoryListApiResponseJsonConverter());
            _jsonOptions.Converters.Add(new CreateCategoryRequestDtoJsonConverter());
            _jsonOptions.Converters.Add(new CreateProductRequestDtoJsonConverter());
            _jsonOptions.Converters.Add(new CreateReservaRequestDtoJsonConverter());
            _jsonOptions.Converters.Add(new EstadoReservaJsonConverter());
            _jsonOptions.Converters.Add(new EstadoReservaNullableJsonConverter());
            _jsonOptions.Converters.Add(new LoginRequestDtoJsonConverter());
            _jsonOptions.Converters.Add(new ObjectApiResponseJsonConverter());
            _jsonOptions.Converters.Add(new ProductJsonConverter());
            _jsonOptions.Converters.Add(new ProductApiResponseJsonConverter());
            _jsonOptions.Converters.Add(new ProductListApiResponseJsonConverter());
            _jsonOptions.Converters.Add(new ReservaJsonConverter());
            _jsonOptions.Converters.Add(new ReservaApiResponseJsonConverter());
            _jsonOptions.Converters.Add(new ReservaListApiResponseJsonConverter());
            _jsonOptions.Converters.Add(new UpdateCategoryRequestDtoJsonConverter());
            _jsonOptions.Converters.Add(new UpdateProductRequestDtoJsonConverter());
            _jsonOptions.Converters.Add(new UpdateReservaRequestDtoJsonConverter());
            JsonSerializerOptionsProvider jsonSerializerOptionsProvider = new(_jsonOptions);
            _services.AddSingleton(jsonSerializerOptionsProvider);
            _services.AddSingleton<IApiFactory, ApiFactory>();
            _services.AddSingleton<AuthApiEvents>();
            _services.AddSingleton<CategoryApiEvents>();
            _services.AddSingleton<ProductApiEvents>();
            _services.AddSingleton<ReservaApiEvents>();
            OnHostConfigurationCreated();
        }

        /// <summary>
        /// Configures the HttpClients.
        /// </summary>
        /// <param name="builder"></param>
        /// <returns></returns>
        public HostConfiguration AddApiHttpClients(Action<IHttpClientBuilder>? builder = null)
        {
            return AddApiHttpClients((Action<IServiceProvider, HttpClient>?)null, builder);
        }

        /// <summary>
        /// Configures the HttpClients.
        /// </summary>
        /// <param name="client"></param>
        /// <param name="builder"></param>
        /// <returns></returns>
        public HostConfiguration AddApiHttpClients(
            Action<HttpClient>? client,
            Action<IHttpClientBuilder>? builder = null)
        {
            var wrapped = client != null ? new Action<IServiceProvider, HttpClient>((_, httpClient) =>
            {
                client(httpClient);
            }) : null;
            return AddApiHttpClients(wrapped, builder);
        }

        /// <summary>
        /// Configures the HttpClients.
        /// </summary>
        /// <param name="client"></param>
        /// <param name="builder"></param>
        /// <returns></returns>
        public HostConfiguration AddApiHttpClients(
            Action<IServiceProvider, HttpClient>? client,
            Action<IHttpClientBuilder>? builder = null)
        {
            if (client == null)
                client = (_, c) => c.BaseAddress = new Uri(ClientUtils.BASE_ADDRESS);

            List<IHttpClientBuilder> builders = new List<IHttpClientBuilder>();

            builders.Add(_services.AddHttpClient<IAuthApi, AuthApi>("MiClienteReservas.Api.IAuthApi", client));
            builders.Add(_services.AddHttpClient<ICategoryApi, CategoryApi>("MiClienteReservas.Api.ICategoryApi", client));
            builders.Add(_services.AddHttpClient<IProductApi, ProductApi>("MiClienteReservas.Api.IProductApi", client));
            builders.Add(_services.AddHttpClient<IReservaApi, ReservaApi>("MiClienteReservas.Api.IReservaApi", client));

            foreach (IHttpClientBuilder instance in builders)
            {
                bool suppressDefault = false;
                OnAddApiHttpClientBuilder(instance, builder, ref suppressDefault);
                if (!suppressDefault)
                    builder?.Invoke(instance);
            }

            HttpClientsAdded = true;

            return this;
        }

        /// <summary>
        /// Applies configuration to each HttpClient.
        /// Implement this partial method to prepend configuration, invoke <paramref name="userBuilder"/> at the
        /// desired position, and append further configuration. Set <paramref name="suppressDefault"/> to
        /// <c>true</c> when you invoke <paramref name="userBuilder"/> yourself to prevent a second invocation,
        /// or to ignore the user's builder entirely.
        /// If this method is not implemented, <paramref name="userBuilder"/> is invoked automatically.
        /// </summary>
        /// <param name="builder">The <see cref="IHttpClientBuilder"/> to configure.</param>
        /// <param name="userBuilder">The caller-supplied builder action, or <c>null</c> if none was provided.</param>
        /// <param name="suppressDefault">Set to <c>true</c> to prevent the default invocation of <paramref name="userBuilder"/>.</param>
        partial void OnAddApiHttpClientBuilder(IHttpClientBuilder builder, Action<IHttpClientBuilder>? userBuilder, ref bool suppressDefault);

        /// <summary>
        /// Called at the end of the constructor after all JSON converters and services are registered.
        /// Implement this partial method to further configure <c>_jsonOptions</c> or register additional singletons via <c>_services</c>.
        /// </summary>
        partial void OnHostConfigurationCreated();

        /// <summary>
        /// Called after all services have been registered.
        /// Implement this partial method to register additional services.
        /// </summary>
        /// <param name="services"></param>
        partial void OnServicesAdded(IServiceCollection services);

        internal void NotifyServicesAdded(IServiceCollection services) => OnServicesAdded(services);

        /// <summary>
        /// Configures the JsonSerializerSettings
        /// </summary>
        /// <param name="options"></param>
        /// <returns></returns>
        public HostConfiguration ConfigureJsonOptions(Action<JsonSerializerOptions> options)
        {
            options(_jsonOptions);

            return this;
        }

        /// <summary>
        /// Adds tokens to your IServiceCollection
        /// </summary>
        /// <typeparam name="TTokenBase"></typeparam>
        /// <param name="token"></param>
        /// <returns></returns>
        public HostConfiguration AddTokens<TTokenBase>(TTokenBase token) where TTokenBase : TokenBase
        {
            return AddTokens(new TTokenBase[]{ token });
        }

        /// <summary>
        /// Adds tokens to your IServiceCollection
        /// </summary>
        /// <typeparam name="TTokenBase"></typeparam>
        /// <param name="tokens"></param>
        /// <returns></returns>
        public HostConfiguration AddTokens<TTokenBase>(IEnumerable<TTokenBase> tokens) where TTokenBase : TokenBase
        {
            TokenContainer<TTokenBase> container = new TokenContainer<TTokenBase>(tokens);
            _services.AddSingleton(services => container);

            return this;
        }

        /// <summary>
        /// Adds a token provider to your IServiceCollection
        /// </summary>
        /// <typeparam name="TTokenProvider"></typeparam>
        /// <typeparam name="TTokenBase"></typeparam>
        /// <returns></returns>
        public HostConfiguration UseProvider<TTokenProvider, TTokenBase>() 
            where TTokenProvider : TokenProvider<TTokenBase>
            where TTokenBase : TokenBase
        {
            _services.AddSingleton<TTokenProvider>();
            _services.AddSingleton<TokenProvider<TTokenBase>>(services => services.GetRequiredService<TTokenProvider>());

            return this;
        }
    }
}
