// <auto-generated>
/*
 * DemoApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using MiClienteReservas.Client;

namespace MiClienteReservas.Model
{
    /// <summary>
    /// Datos necesarios para crear un producto.
    /// </summary>
    public partial class CreateProductRequestDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateProductRequestDto" /> class.
        /// </summary>
        /// <param name="name">Nombre del producto.</param>
        /// <param name="sku">Código único del producto.</param>
        /// <param name="price">Precio del producto.</param>
        /// <param name="categoryId">Identificador de la categoría del producto.</param>
        /// <param name="isActive">Valor que indica si el producto está activo.</param>
        [JsonConstructor]
        public CreateProductRequestDto(string name, string sku, Option<double?> price = default, Option<int?> categoryId = default, Option<bool?> isActive = default)
        {
            Name = name;
            Sku = sku;
            PriceOption = price;
            CategoryIdOption = categoryId;
            IsActiveOption = isActive;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Nombre del producto.
        /// </summary>
        /// <value>Nombre del producto.</value>
        [JsonPropertyName("name")]
        public string Name { get; set; }

        /// <summary>
        /// Código único del producto.
        /// </summary>
        /// <value>Código único del producto.</value>
        [JsonPropertyName("sku")]
        public string Sku { get; set; }

        /// <summary>
        /// Used to track the state of Price
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<double?> PriceOption { get; private set; }

        /// <summary>
        /// Precio del producto.
        /// </summary>
        /// <value>Precio del producto.</value>
        [JsonPropertyName("price")]
        public double? Price { get { return this.PriceOption.Value; } set { this.PriceOption = new(value); } }

        /// <summary>
        /// Used to track the state of CategoryId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> CategoryIdOption { get; private set; }

        /// <summary>
        /// Identificador de la categoría del producto.
        /// </summary>
        /// <value>Identificador de la categoría del producto.</value>
        [JsonPropertyName("categoryId")]
        public int? CategoryId { get { return this.CategoryIdOption.Value; } set { this.CategoryIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of IsActive
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> IsActiveOption { get; private set; }

        /// <summary>
        /// Valor que indica si el producto está activo.
        /// </summary>
        /// <value>Valor que indica si el producto está activo.</value>
        [JsonPropertyName("isActive")]
        public bool? IsActive { get { return this.IsActiveOption.Value; } set { this.IsActiveOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateProductRequestDto {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Sku: ").Append(Sku).Append("\n");
            sb.Append("  Price: ").Append(Price).Append("\n");
            sb.Append("  CategoryId: ").Append(CategoryId).Append("\n");
            sb.Append("  IsActive: ").Append(IsActive).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Name (string) maxLength
            if (this.Name != null && this.Name.Length > 200)
            {
                yield return new ValidationResult("Invalid value for Name, length must be less than 200.", new [] { "Name" });
            }

            // Name (string) minLength
            if (this.Name != null && this.Name.Length < 2)
            {
                yield return new ValidationResult("Invalid value for Name, length must be greater than 2.", new [] { "Name" });
            }

            // Sku (string) maxLength
            if (this.Sku != null && this.Sku.Length > 50)
            {
                yield return new ValidationResult("Invalid value for Sku, length must be less than 50.", new [] { "Sku" });
            }

            // Sku (string) minLength
            if (this.Sku != null && this.Sku.Length < 3)
            {
                yield return new ValidationResult("Invalid value for Sku, length must be greater than 3.", new [] { "Sku" });
            }

            if (this.Sku != null) {
                // Sku (string) pattern
                Regex regexSku = new Regex(@"^[A-Za-z0-9-]+$", RegexOptions.CultureInvariant);

                if (!regexSku.Match(this.Sku).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Sku, must match a pattern of " + regexSku, new [] { "Sku" });
                }
            }

            // Price (double) maximum
            if (this.PriceOption.IsSet && this.PriceOption.Value > (double)1000000)
            {
                yield return new ValidationResult("Invalid value for Price, must be a value less than or equal to 1000000.", new [] { "Price" });
            }

            // Price (double) minimum
            if (this.PriceOption.IsSet && this.PriceOption.Value < (double)0.01)
            {
                yield return new ValidationResult("Invalid value for Price, must be a value greater than or equal to 0.01.", new [] { "Price" });
            }

            // CategoryId (int) maximum
            if (this.CategoryIdOption.IsSet && this.CategoryIdOption.Value > (int)2147483647)
            {
                yield return new ValidationResult("Invalid value for CategoryId, must be a value less than or equal to 2147483647.", new [] { "CategoryId" });
            }

            // CategoryId (int) minimum
            if (this.CategoryIdOption.IsSet && this.CategoryIdOption.Value < (int)1)
            {
                yield return new ValidationResult("Invalid value for CategoryId, must be a value greater than or equal to 1.", new [] { "CategoryId" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="CreateProductRequestDto" />
    /// </summary>
    public partial class CreateProductRequestDtoJsonConverter : JsonConverter<CreateProductRequestDto>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="CreateProductRequestDtoJsonConverter" /> class.
        /// </summary>
        public CreateProductRequestDtoJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="CreateProductRequestDto" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override CreateProductRequestDto Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> name = default;
            Option<string?> sku = default;
            Option<double?> price = default;
            Option<int?> categoryId = default;
            Option<bool?> isActive = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "sku":
                            sku = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "price":
                            price = new Option<double?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (double?)null : utf8JsonReader.GetDouble());
                            break;
                        case "categoryId":
                            categoryId = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "isActive":
                            isActive = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!name.IsSet)
                throw new ArgumentException("Property is required for class CreateProductRequestDto.", nameof(name));

            if (!sku.IsSet)
                throw new ArgumentException("Property is required for class CreateProductRequestDto.", nameof(sku));

            if (name.IsSet && name.Value == null)
                throw new ArgumentNullException(nameof(name), "Property is not nullable for class CreateProductRequestDto.");

            if (sku.IsSet && sku.Value == null)
                throw new ArgumentNullException(nameof(sku), "Property is not nullable for class CreateProductRequestDto.");

            if (price.IsSet && price.Value == null)
                throw new ArgumentNullException(nameof(price), "Property is not nullable for class CreateProductRequestDto.");

            if (categoryId.IsSet && categoryId.Value == null)
                throw new ArgumentNullException(nameof(categoryId), "Property is not nullable for class CreateProductRequestDto.");

            if (isActive.IsSet && isActive.Value == null)
                throw new ArgumentNullException(nameof(isActive), "Property is not nullable for class CreateProductRequestDto.");

            return new CreateProductRequestDto(name.Value!, sku.Value!, price, categoryId, isActive);
        }

        /// <summary>
        /// Serializes a <see cref="CreateProductRequestDto" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="createProductRequestDto"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, CreateProductRequestDto createProductRequestDto, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, createProductRequestDto, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="CreateProductRequestDto" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="createProductRequestDto"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, CreateProductRequestDto createProductRequestDto, JsonSerializerOptions jsonSerializerOptions)
        {
            if (createProductRequestDto.Name == null)
                throw new ArgumentNullException(nameof(createProductRequestDto.Name), "Property is required for class CreateProductRequestDto.");

            if (createProductRequestDto.Sku == null)
                throw new ArgumentNullException(nameof(createProductRequestDto.Sku), "Property is required for class CreateProductRequestDto.");

            writer.WriteString("name", createProductRequestDto.Name);

            writer.WriteString("sku", createProductRequestDto.Sku);

            if (createProductRequestDto.PriceOption.IsSet)
                writer.WriteNumber("price", createProductRequestDto.PriceOption.Value!.Value);

            if (createProductRequestDto.CategoryIdOption.IsSet)
                writer.WriteNumber("categoryId", createProductRequestDto.CategoryIdOption.Value!.Value);

            if (createProductRequestDto.IsActiveOption.IsSet)
                writer.WriteBoolean("isActive", createProductRequestDto.IsActiveOption.Value!.Value);
        }
    }
}
