// <auto-generated>
/*
 * DemoApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using MiClienteReservas.Client;

namespace MiClienteReservas.Model
{
    /// <summary>
    /// Datos necesarios para registrar una reserva.
    /// </summary>
    public partial class CreateReservaRequestDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateReservaRequestDto" /> class.
        /// </summary>
        /// <param name="nombreSala">Nombre de la sala a reservar.</param>
        /// <param name="fechaReserva">Fecha de la reserva (yyyy-MM-dd).</param>
        /// <param name="horaInicio">Hora de inicio (HH:mm:ss).</param>
        /// <param name="horaFin">Hora de fin (HH:mm:ss). Debe ser posterior a la hora de inicio.</param>
        /// <param name="nombreResponsable">Nombre del responsable de la reserva.</param>
        /// <param name="motivo">Motivo de la reunión.</param>
        /// <param name="cantidadAsistentes">Cantidad de asistentes. Debe ser mayor a cero.</param>
        [JsonConstructor]
        public CreateReservaRequestDto(string nombreSala, DateOnly fechaReserva, string horaInicio, string horaFin, string nombreResponsable, string motivo, Option<int?> cantidadAsistentes = default)
        {
            NombreSala = nombreSala;
            FechaReserva = fechaReserva;
            HoraInicio = horaInicio;
            HoraFin = horaFin;
            NombreResponsable = nombreResponsable;
            Motivo = motivo;
            CantidadAsistentesOption = cantidadAsistentes;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Nombre de la sala a reservar.
        /// </summary>
        /// <value>Nombre de la sala a reservar.</value>
        [JsonPropertyName("nombreSala")]
        public string NombreSala { get; set; }

        /// <summary>
        /// Fecha de la reserva (yyyy-MM-dd).
        /// </summary>
        /// <value>Fecha de la reserva (yyyy-MM-dd).</value>
        [JsonPropertyName("fechaReserva")]
        public DateOnly FechaReserva { get; set; }

        /// <summary>
        /// Hora de inicio (HH:mm:ss).
        /// </summary>
        /// <value>Hora de inicio (HH:mm:ss).</value>
        [JsonPropertyName("horaInicio")]
        public string HoraInicio { get; set; }

        /// <summary>
        /// Hora de fin (HH:mm:ss). Debe ser posterior a la hora de inicio.
        /// </summary>
        /// <value>Hora de fin (HH:mm:ss). Debe ser posterior a la hora de inicio.</value>
        [JsonPropertyName("horaFin")]
        public string HoraFin { get; set; }

        /// <summary>
        /// Nombre del responsable de la reserva.
        /// </summary>
        /// <value>Nombre del responsable de la reserva.</value>
        [JsonPropertyName("nombreResponsable")]
        public string NombreResponsable { get; set; }

        /// <summary>
        /// Motivo de la reunión.
        /// </summary>
        /// <value>Motivo de la reunión.</value>
        [JsonPropertyName("motivo")]
        public string Motivo { get; set; }

        /// <summary>
        /// Used to track the state of CantidadAsistentes
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> CantidadAsistentesOption { get; private set; }

        /// <summary>
        /// Cantidad de asistentes. Debe ser mayor a cero.
        /// </summary>
        /// <value>Cantidad de asistentes. Debe ser mayor a cero.</value>
        [JsonPropertyName("cantidadAsistentes")]
        public int? CantidadAsistentes { get { return this.CantidadAsistentesOption.Value; } set { this.CantidadAsistentesOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateReservaRequestDto {\n");
            sb.Append("  NombreSala: ").Append(NombreSala).Append("\n");
            sb.Append("  FechaReserva: ").Append(FechaReserva).Append("\n");
            sb.Append("  HoraInicio: ").Append(HoraInicio).Append("\n");
            sb.Append("  HoraFin: ").Append(HoraFin).Append("\n");
            sb.Append("  NombreResponsable: ").Append(NombreResponsable).Append("\n");
            sb.Append("  Motivo: ").Append(Motivo).Append("\n");
            sb.Append("  CantidadAsistentes: ").Append(CantidadAsistentes).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // NombreSala (string) maxLength
            if (this.NombreSala != null && this.NombreSala.Length > 100)
            {
                yield return new ValidationResult("Invalid value for NombreSala, length must be less than 100.", new [] { "NombreSala" });
            }

            // NombreSala (string) minLength
            if (this.NombreSala != null && this.NombreSala.Length < 2)
            {
                yield return new ValidationResult("Invalid value for NombreSala, length must be greater than 2.", new [] { "NombreSala" });
            }

            // NombreResponsable (string) maxLength
            if (this.NombreResponsable != null && this.NombreResponsable.Length > 150)
            {
                yield return new ValidationResult("Invalid value for NombreResponsable, length must be less than 150.", new [] { "NombreResponsable" });
            }

            // NombreResponsable (string) minLength
            if (this.NombreResponsable != null && this.NombreResponsable.Length < 2)
            {
                yield return new ValidationResult("Invalid value for NombreResponsable, length must be greater than 2.", new [] { "NombreResponsable" });
            }

            // Motivo (string) maxLength
            if (this.Motivo != null && this.Motivo.Length > 300)
            {
                yield return new ValidationResult("Invalid value for Motivo, length must be less than 300.", new [] { "Motivo" });
            }

            // Motivo (string) minLength
            if (this.Motivo != null && this.Motivo.Length < 3)
            {
                yield return new ValidationResult("Invalid value for Motivo, length must be greater than 3.", new [] { "Motivo" });
            }

            // CantidadAsistentes (int) maximum
            if (this.CantidadAsistentesOption.IsSet && this.CantidadAsistentesOption.Value > (int)1000)
            {
                yield return new ValidationResult("Invalid value for CantidadAsistentes, must be a value less than or equal to 1000.", new [] { "CantidadAsistentes" });
            }

            // CantidadAsistentes (int) minimum
            if (this.CantidadAsistentesOption.IsSet && this.CantidadAsistentesOption.Value < (int)1)
            {
                yield return new ValidationResult("Invalid value for CantidadAsistentes, must be a value greater than or equal to 1.", new [] { "CantidadAsistentes" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="CreateReservaRequestDto" />
    /// </summary>
    public partial class CreateReservaRequestDtoJsonConverter : JsonConverter<CreateReservaRequestDto>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="CreateReservaRequestDtoJsonConverter" /> class.
        /// </summary>
        public CreateReservaRequestDtoJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// The format to use to serialize FechaReserva
        /// </summary>
        public string FechaReservaFormat { get; private set; } = "yyyy'-'MM'-'dd";

        /// <summary>
        /// Deserializes json to <see cref="CreateReservaRequestDto" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override CreateReservaRequestDto Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> nombreSala = default;
            Option<DateOnly?> fechaReserva = default;
            Option<string?> horaInicio = default;
            Option<string?> horaFin = default;
            Option<string?> nombreResponsable = default;
            Option<string?> motivo = default;
            Option<int?> cantidadAsistentes = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "nombreSala":
                            nombreSala = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "fechaReserva":
                            fechaReserva = new Option<DateOnly?>(JsonSerializer.Deserialize<DateOnly>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "horaInicio":
                            horaInicio = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "horaFin":
                            horaFin = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "nombreResponsable":
                            nombreResponsable = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "motivo":
                            motivo = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "cantidadAsistentes":
                            cantidadAsistentes = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!nombreSala.IsSet)
                throw new ArgumentException("Property is required for class CreateReservaRequestDto.", nameof(nombreSala));

            if (!fechaReserva.IsSet)
                throw new ArgumentException("Property is required for class CreateReservaRequestDto.", nameof(fechaReserva));

            if (!horaInicio.IsSet)
                throw new ArgumentException("Property is required for class CreateReservaRequestDto.", nameof(horaInicio));

            if (!horaFin.IsSet)
                throw new ArgumentException("Property is required for class CreateReservaRequestDto.", nameof(horaFin));

            if (!nombreResponsable.IsSet)
                throw new ArgumentException("Property is required for class CreateReservaRequestDto.", nameof(nombreResponsable));

            if (!motivo.IsSet)
                throw new ArgumentException("Property is required for class CreateReservaRequestDto.", nameof(motivo));

            if (nombreSala.IsSet && nombreSala.Value == null)
                throw new ArgumentNullException(nameof(nombreSala), "Property is not nullable for class CreateReservaRequestDto.");

            if (fechaReserva.IsSet && fechaReserva.Value == null)
                throw new ArgumentNullException(nameof(fechaReserva), "Property is not nullable for class CreateReservaRequestDto.");

            if (horaInicio.IsSet && horaInicio.Value == null)
                throw new ArgumentNullException(nameof(horaInicio), "Property is not nullable for class CreateReservaRequestDto.");

            if (horaFin.IsSet && horaFin.Value == null)
                throw new ArgumentNullException(nameof(horaFin), "Property is not nullable for class CreateReservaRequestDto.");

            if (nombreResponsable.IsSet && nombreResponsable.Value == null)
                throw new ArgumentNullException(nameof(nombreResponsable), "Property is not nullable for class CreateReservaRequestDto.");

            if (motivo.IsSet && motivo.Value == null)
                throw new ArgumentNullException(nameof(motivo), "Property is not nullable for class CreateReservaRequestDto.");

            if (cantidadAsistentes.IsSet && cantidadAsistentes.Value == null)
                throw new ArgumentNullException(nameof(cantidadAsistentes), "Property is not nullable for class CreateReservaRequestDto.");

            return new CreateReservaRequestDto(nombreSala.Value!, fechaReserva.Value!.Value!, horaInicio.Value!, horaFin.Value!, nombreResponsable.Value!, motivo.Value!, cantidadAsistentes);
        }

        /// <summary>
        /// Serializes a <see cref="CreateReservaRequestDto" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="createReservaRequestDto"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, CreateReservaRequestDto createReservaRequestDto, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, createReservaRequestDto, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="CreateReservaRequestDto" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="createReservaRequestDto"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, CreateReservaRequestDto createReservaRequestDto, JsonSerializerOptions jsonSerializerOptions)
        {
            if (createReservaRequestDto.NombreSala == null)
                throw new ArgumentNullException(nameof(createReservaRequestDto.NombreSala), "Property is required for class CreateReservaRequestDto.");

            if (createReservaRequestDto.HoraInicio == null)
                throw new ArgumentNullException(nameof(createReservaRequestDto.HoraInicio), "Property is required for class CreateReservaRequestDto.");

            if (createReservaRequestDto.HoraFin == null)
                throw new ArgumentNullException(nameof(createReservaRequestDto.HoraFin), "Property is required for class CreateReservaRequestDto.");

            if (createReservaRequestDto.NombreResponsable == null)
                throw new ArgumentNullException(nameof(createReservaRequestDto.NombreResponsable), "Property is required for class CreateReservaRequestDto.");

            if (createReservaRequestDto.Motivo == null)
                throw new ArgumentNullException(nameof(createReservaRequestDto.Motivo), "Property is required for class CreateReservaRequestDto.");

            writer.WriteString("nombreSala", createReservaRequestDto.NombreSala);

            writer.WriteString("fechaReserva", createReservaRequestDto.FechaReserva.ToString(FechaReservaFormat));

            writer.WriteString("horaInicio", createReservaRequestDto.HoraInicio);

            writer.WriteString("horaFin", createReservaRequestDto.HoraFin);

            writer.WriteString("nombreResponsable", createReservaRequestDto.NombreResponsable);

            writer.WriteString("motivo", createReservaRequestDto.Motivo);

            if (createReservaRequestDto.CantidadAsistentesOption.IsSet)
                writer.WriteNumber("cantidadAsistentes", createReservaRequestDto.CantidadAsistentesOption.Value!.Value);
        }
    }
}
