// <auto-generated>
/*
 * DemoApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using MiClienteReservas.Client;

namespace MiClienteReservas.Model
{
    /// <summary>
    /// Estados posibles de una reserva.
    /// </summary>
    /// <value>Estados posibles de una reserva.</value>
    public enum EstadoReserva
    {
        /// <summary>
        /// Enum Pendiente for value: Pendiente
        /// </summary>
        Pendiente = 1,

        /// <summary>
        /// Enum Confirmada for value: Confirmada
        /// </summary>
        Confirmada = 2,

        /// <summary>
        /// Enum Cancelada for value: Cancelada
        /// </summary>
        Cancelada = 3
    }

    /// <summary>
    /// Converts <see cref="EstadoReserva"/> to and from the JSON value
    /// </summary>
    public static class EstadoReservaValueConverter
    {
        /// <summary>
        /// Parses a given value to <see cref="EstadoReserva"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static EstadoReserva FromString(string value)
        {
            if (value.Equals("Pendiente"))
                return EstadoReserva.Pendiente;

            if (value.Equals("Confirmada"))
                return EstadoReserva.Confirmada;

            if (value.Equals("Cancelada"))
                return EstadoReserva.Cancelada;

            throw new NotImplementedException($"Could not convert value to type EstadoReserva: '{value}'");
        }

        /// <summary>
        /// Parses a given value to <see cref="EstadoReserva"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static EstadoReserva? FromStringOrDefault(string value)
        {
            if (value.Equals("Pendiente"))
                return EstadoReserva.Pendiente;

            if (value.Equals("Confirmada"))
                return EstadoReserva.Confirmada;

            if (value.Equals("Cancelada"))
                return EstadoReserva.Cancelada;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="EstadoReserva"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string ToJsonValue(EstadoReserva value)
        {
            if (value == EstadoReserva.Pendiente)
                return "Pendiente";

            if (value == EstadoReserva.Confirmada)
                return "Confirmada";

            if (value == EstadoReserva.Cancelada)
                return "Cancelada";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="EstadoReserva"/>
    /// </summary>
    /// <exception cref="NotImplementedException"></exception>
    public class EstadoReservaJsonConverter : JsonConverter<EstadoReserva>
    {
        /// <summary>
        /// Returns a  from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override EstadoReserva Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            EstadoReserva? result = rawValue == null
                ? null
                : EstadoReservaValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the EstadoReserva to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="estadoReserva"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, EstadoReserva estadoReserva, JsonSerializerOptions options)
        {
            writer.WriteStringValue(EstadoReservaValueConverter.ToJsonValue(estadoReserva).ToString());
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="EstadoReserva"/>
    /// </summary>
    public class EstadoReservaNullableJsonConverter : JsonConverter<EstadoReserva?>
    {
        /// <summary>
        /// Returns a EstadoReserva from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override EstadoReserva? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            if (reader.TokenType == JsonTokenType.Null)
                return null;

            string? rawValue = reader.GetString();

            EstadoReserva? result = rawValue == null
                ? null
                : EstadoReservaValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the EstadoReserva to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="estadoReserva"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, EstadoReserva? estadoReserva, JsonSerializerOptions options)
        {
            if (estadoReserva.HasValue)
                writer.WriteStringValue(EstadoReservaValueConverter.ToJsonValue(estadoReserva.Value).ToString());
            else
                writer.WriteNullValue();
        }
    }
}
