// <auto-generated>
/*
 * DemoApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using MiClienteReservas.Client;

namespace MiClienteReservas.Model
{
    /// <summary>
    /// Representa un producto disponible en el catálogo.
    /// </summary>
    public partial class Product : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Product" /> class.
        /// </summary>
        /// <param name="id">Identificador único del producto.</param>
        /// <param name="name">Nombre visible del producto.</param>
        /// <param name="sku">Código único del producto.</param>
        /// <param name="price">Precio del producto.</param>
        /// <param name="categoryId">Identificador de la categoría del producto.</param>
        /// <param name="category">Categoría a la que pertenece el producto.</param>
        /// <param name="isActive">Indica si el producto está activo.</param>
        /// <param name="createdAt">Fecha de creación del registro.</param>
        [JsonConstructor]
        public Product(Option<int?> id = default, Option<string?> name = default, Option<string?> sku = default, Option<double?> price = default, Option<int?> categoryId = default, Option<Category?> category = default, Option<bool?> isActive = default, Option<DateTime?> createdAt = default)
        {
            IdOption = id;
            NameOption = name;
            SkuOption = sku;
            PriceOption = price;
            CategoryIdOption = categoryId;
            CategoryOption = category;
            IsActiveOption = isActive;
            CreatedAtOption = createdAt;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Id
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> IdOption { get; private set; }

        /// <summary>
        /// Identificador único del producto.
        /// </summary>
        /// <value>Identificador único del producto.</value>
        [JsonPropertyName("id")]
        public int? Id { get { return this.IdOption.Value; } set { this.IdOption = new(value); } }

        /// <summary>
        /// Used to track the state of Name
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> NameOption { get; private set; }

        /// <summary>
        /// Nombre visible del producto.
        /// </summary>
        /// <value>Nombre visible del producto.</value>
        [JsonPropertyName("name")]
        public string? Name { get { return this.NameOption.Value; } set { this.NameOption = new(value); } }

        /// <summary>
        /// Used to track the state of Sku
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> SkuOption { get; private set; }

        /// <summary>
        /// Código único del producto.
        /// </summary>
        /// <value>Código único del producto.</value>
        [JsonPropertyName("sku")]
        public string? Sku { get { return this.SkuOption.Value; } set { this.SkuOption = new(value); } }

        /// <summary>
        /// Used to track the state of Price
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<double?> PriceOption { get; private set; }

        /// <summary>
        /// Precio del producto.
        /// </summary>
        /// <value>Precio del producto.</value>
        [JsonPropertyName("price")]
        public double? Price { get { return this.PriceOption.Value; } set { this.PriceOption = new(value); } }

        /// <summary>
        /// Used to track the state of CategoryId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> CategoryIdOption { get; private set; }

        /// <summary>
        /// Identificador de la categoría del producto.
        /// </summary>
        /// <value>Identificador de la categoría del producto.</value>
        [JsonPropertyName("categoryId")]
        public int? CategoryId { get { return this.CategoryIdOption.Value; } set { this.CategoryIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of Category
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Category?> CategoryOption { get; private set; }

        /// <summary>
        /// Categoría a la que pertenece el producto.
        /// </summary>
        /// <value>Categoría a la que pertenece el producto.</value>
        [JsonPropertyName("category")]
        public Category? Category { get { return this.CategoryOption.Value; } set { this.CategoryOption = new(value); } }

        /// <summary>
        /// Used to track the state of IsActive
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> IsActiveOption { get; private set; }

        /// <summary>
        /// Indica si el producto está activo.
        /// </summary>
        /// <value>Indica si el producto está activo.</value>
        [JsonPropertyName("isActive")]
        public bool? IsActive { get { return this.IsActiveOption.Value; } set { this.IsActiveOption = new(value); } }

        /// <summary>
        /// Used to track the state of CreatedAt
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTime?> CreatedAtOption { get; private set; }

        /// <summary>
        /// Fecha de creación del registro.
        /// </summary>
        /// <value>Fecha de creación del registro.</value>
        [JsonPropertyName("createdAt")]
        public DateTime? CreatedAt { get { return this.CreatedAtOption.Value; } set { this.CreatedAtOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Product {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Sku: ").Append(Sku).Append("\n");
            sb.Append("  Price: ").Append(Price).Append("\n");
            sb.Append("  CategoryId: ").Append(CategoryId).Append("\n");
            sb.Append("  Category: ").Append(Category).Append("\n");
            sb.Append("  IsActive: ").Append(IsActive).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="Product" />
    /// </summary>
    public partial class ProductJsonConverter : JsonConverter<Product>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="ProductJsonConverter" /> class.
        /// </summary>
        public ProductJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// The format to use to serialize CreatedAt
        /// </summary>
        public string CreatedAtFormat { get; private set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="Product" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override Product Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<int?> id = default;
            Option<string?> name = default;
            Option<string?> sku = default;
            Option<double?> price = default;
            Option<int?> categoryId = default;
            Option<Category?> category = default;
            Option<bool?> isActive = default;
            Option<DateTime?> createdAt = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "id":
                            id = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "sku":
                            sku = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "price":
                            price = new Option<double?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (double?)null : utf8JsonReader.GetDouble());
                            break;
                        case "categoryId":
                            categoryId = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "category":
                            category = new Option<Category?>(JsonSerializer.Deserialize<Category>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "isActive":
                            isActive = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "createdAt":
                            createdAt = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class Product.");

            if (price.IsSet && price.Value == null)
                throw new ArgumentNullException(nameof(price), "Property is not nullable for class Product.");

            if (categoryId.IsSet && categoryId.Value == null)
                throw new ArgumentNullException(nameof(categoryId), "Property is not nullable for class Product.");

            if (isActive.IsSet && isActive.Value == null)
                throw new ArgumentNullException(nameof(isActive), "Property is not nullable for class Product.");

            if (createdAt.IsSet && createdAt.Value == null)
                throw new ArgumentNullException(nameof(createdAt), "Property is not nullable for class Product.");

            return new Product(id, name, sku, price, categoryId, category, isActive, createdAt);
        }

        /// <summary>
        /// Serializes a <see cref="Product" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="product"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, Product product, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, product, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="Product" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="product"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, Product product, JsonSerializerOptions jsonSerializerOptions)
        {
            if (product.IdOption.IsSet)
                writer.WriteNumber("id", product.IdOption.Value!.Value);

            if (product.NameOption.IsSet)
                if (product.NameOption.Value != null)
                    writer.WriteString("name", product.Name);
                else
                    writer.WriteNull("name");

            if (product.SkuOption.IsSet)
                if (product.SkuOption.Value != null)
                    writer.WriteString("sku", product.Sku);
                else
                    writer.WriteNull("sku");

            if (product.PriceOption.IsSet)
                writer.WriteNumber("price", product.PriceOption.Value!.Value);

            if (product.CategoryIdOption.IsSet)
                writer.WriteNumber("categoryId", product.CategoryIdOption.Value!.Value);

            if (product.CategoryOption.IsSet)
                if (product.CategoryOption.Value != null)
                {
                    writer.WritePropertyName("category");
                    JsonSerializer.Serialize(writer, product.Category, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("category");
            if (product.IsActiveOption.IsSet)
                writer.WriteBoolean("isActive", product.IsActiveOption.Value!.Value);

            if (product.CreatedAtOption.IsSet)
                writer.WriteString("createdAt", product.CreatedAtOption.Value!.Value.ToString(CreatedAtFormat));
        }
    }
}
