// <auto-generated>
/*
 * DemoApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using MiClienteReservas.Client;

namespace MiClienteReservas.Model
{
    /// <summary>
    /// Representa la reserva de una sala de reuniones.
    /// </summary>
    public partial class Reserva : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Reserva" /> class.
        /// </summary>
        /// <param name="id">Identificador único de la reserva.</param>
        /// <param name="nombreSala">Nombre de la sala reservada.</param>
        /// <param name="fechaReserva">Fecha de la reserva.</param>
        /// <param name="horaInicio">Hora de inicio de la reunión.</param>
        /// <param name="horaFin">Hora de fin de la reunión.</param>
        /// <param name="nombreResponsable">Nombre de la persona responsable de la reserva.</param>
        /// <param name="cantidadAsistentes">Cantidad de asistentes a la reunión.</param>
        /// <param name="motivo">Motivo de la reunión.</param>
        /// <param name="estado">Estado actual de la reserva.</param>
        [JsonConstructor]
        public Reserva(Option<int?> id = default, Option<string?> nombreSala = default, Option<DateOnly?> fechaReserva = default, Option<string?> horaInicio = default, Option<string?> horaFin = default, Option<string?> nombreResponsable = default, Option<int?> cantidadAsistentes = default, Option<string?> motivo = default, Option<EstadoReserva?> estado = default)
        {
            IdOption = id;
            NombreSalaOption = nombreSala;
            FechaReservaOption = fechaReserva;
            HoraInicioOption = horaInicio;
            HoraFinOption = horaFin;
            NombreResponsableOption = nombreResponsable;
            CantidadAsistentesOption = cantidadAsistentes;
            MotivoOption = motivo;
            EstadoOption = estado;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Estado
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<EstadoReserva?> EstadoOption { get; private set; }

        /// <summary>
        /// Estado actual de la reserva.
        /// </summary>
        /// <value>Estado actual de la reserva.</value>
        [JsonPropertyName("estado")]
        public EstadoReserva? Estado { get { return this.EstadoOption.Value; } set { this.EstadoOption = new(value); } }

        /// <summary>
        /// Used to track the state of Id
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> IdOption { get; private set; }

        /// <summary>
        /// Identificador único de la reserva.
        /// </summary>
        /// <value>Identificador único de la reserva.</value>
        [JsonPropertyName("id")]
        public int? Id { get { return this.IdOption.Value; } set { this.IdOption = new(value); } }

        /// <summary>
        /// Used to track the state of NombreSala
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> NombreSalaOption { get; private set; }

        /// <summary>
        /// Nombre de la sala reservada.
        /// </summary>
        /// <value>Nombre de la sala reservada.</value>
        [JsonPropertyName("nombreSala")]
        public string? NombreSala { get { return this.NombreSalaOption.Value; } set { this.NombreSalaOption = new(value); } }

        /// <summary>
        /// Used to track the state of FechaReserva
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateOnly?> FechaReservaOption { get; private set; }

        /// <summary>
        /// Fecha de la reserva.
        /// </summary>
        /// <value>Fecha de la reserva.</value>
        [JsonPropertyName("fechaReserva")]
        public DateOnly? FechaReserva { get { return this.FechaReservaOption.Value; } set { this.FechaReservaOption = new(value); } }

        /// <summary>
        /// Used to track the state of HoraInicio
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> HoraInicioOption { get; private set; }

        /// <summary>
        /// Hora de inicio de la reunión.
        /// </summary>
        /// <value>Hora de inicio de la reunión.</value>
        [JsonPropertyName("horaInicio")]
        public string? HoraInicio { get { return this.HoraInicioOption.Value; } set { this.HoraInicioOption = new(value); } }

        /// <summary>
        /// Used to track the state of HoraFin
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> HoraFinOption { get; private set; }

        /// <summary>
        /// Hora de fin de la reunión.
        /// </summary>
        /// <value>Hora de fin de la reunión.</value>
        [JsonPropertyName("horaFin")]
        public string? HoraFin { get { return this.HoraFinOption.Value; } set { this.HoraFinOption = new(value); } }

        /// <summary>
        /// Used to track the state of NombreResponsable
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> NombreResponsableOption { get; private set; }

        /// <summary>
        /// Nombre de la persona responsable de la reserva.
        /// </summary>
        /// <value>Nombre de la persona responsable de la reserva.</value>
        [JsonPropertyName("nombreResponsable")]
        public string? NombreResponsable { get { return this.NombreResponsableOption.Value; } set { this.NombreResponsableOption = new(value); } }

        /// <summary>
        /// Used to track the state of CantidadAsistentes
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> CantidadAsistentesOption { get; private set; }

        /// <summary>
        /// Cantidad de asistentes a la reunión.
        /// </summary>
        /// <value>Cantidad de asistentes a la reunión.</value>
        [JsonPropertyName("cantidadAsistentes")]
        public int? CantidadAsistentes { get { return this.CantidadAsistentesOption.Value; } set { this.CantidadAsistentesOption = new(value); } }

        /// <summary>
        /// Used to track the state of Motivo
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> MotivoOption { get; private set; }

        /// <summary>
        /// Motivo de la reunión.
        /// </summary>
        /// <value>Motivo de la reunión.</value>
        [JsonPropertyName("motivo")]
        public string? Motivo { get { return this.MotivoOption.Value; } set { this.MotivoOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Reserva {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  NombreSala: ").Append(NombreSala).Append("\n");
            sb.Append("  FechaReserva: ").Append(FechaReserva).Append("\n");
            sb.Append("  HoraInicio: ").Append(HoraInicio).Append("\n");
            sb.Append("  HoraFin: ").Append(HoraFin).Append("\n");
            sb.Append("  NombreResponsable: ").Append(NombreResponsable).Append("\n");
            sb.Append("  CantidadAsistentes: ").Append(CantidadAsistentes).Append("\n");
            sb.Append("  Motivo: ").Append(Motivo).Append("\n");
            sb.Append("  Estado: ").Append(Estado).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="Reserva" />
    /// </summary>
    public partial class ReservaJsonConverter : JsonConverter<Reserva>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="ReservaJsonConverter" /> class.
        /// </summary>
        public ReservaJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// The format to use to serialize FechaReserva
        /// </summary>
        public string FechaReservaFormat { get; private set; } = "yyyy'-'MM'-'dd";

        /// <summary>
        /// Deserializes json to <see cref="Reserva" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override Reserva Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<int?> id = default;
            Option<string?> nombreSala = default;
            Option<DateOnly?> fechaReserva = default;
            Option<string?> horaInicio = default;
            Option<string?> horaFin = default;
            Option<string?> nombreResponsable = default;
            Option<int?> cantidadAsistentes = default;
            Option<string?> motivo = default;
            Option<EstadoReserva?> estado = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "id":
                            id = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "nombreSala":
                            nombreSala = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "fechaReserva":
                            fechaReserva = new Option<DateOnly?>(JsonSerializer.Deserialize<DateOnly>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "horaInicio":
                            horaInicio = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "horaFin":
                            horaFin = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "nombreResponsable":
                            nombreResponsable = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "cantidadAsistentes":
                            cantidadAsistentes = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "motivo":
                            motivo = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "estado":
                            estado = new Option<EstadoReserva?>(JsonSerializer.Deserialize<EstadoReserva?>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class Reserva.");

            if (fechaReserva.IsSet && fechaReserva.Value == null)
                throw new ArgumentNullException(nameof(fechaReserva), "Property is not nullable for class Reserva.");

            if (horaInicio.IsSet && horaInicio.Value == null)
                throw new ArgumentNullException(nameof(horaInicio), "Property is not nullable for class Reserva.");

            if (horaFin.IsSet && horaFin.Value == null)
                throw new ArgumentNullException(nameof(horaFin), "Property is not nullable for class Reserva.");

            if (cantidadAsistentes.IsSet && cantidadAsistentes.Value == null)
                throw new ArgumentNullException(nameof(cantidadAsistentes), "Property is not nullable for class Reserva.");

            if (estado.IsSet && estado.Value == null)
                throw new ArgumentNullException(nameof(estado), "Property is not nullable for class Reserva.");

            return new Reserva(id, nombreSala, fechaReserva, horaInicio, horaFin, nombreResponsable, cantidadAsistentes, motivo, estado);
        }

        /// <summary>
        /// Serializes a <see cref="Reserva" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="reserva"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, Reserva reserva, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, reserva, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="Reserva" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="reserva"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, Reserva reserva, JsonSerializerOptions jsonSerializerOptions)
        {
            if (reserva.HoraInicioOption.IsSet && reserva.HoraInicio == null)
                throw new ArgumentNullException(nameof(reserva.HoraInicio), "Property is required for class Reserva.");

            if (reserva.HoraFinOption.IsSet && reserva.HoraFin == null)
                throw new ArgumentNullException(nameof(reserva.HoraFin), "Property is required for class Reserva.");

            if (reserva.IdOption.IsSet)
                writer.WriteNumber("id", reserva.IdOption.Value!.Value);

            if (reserva.NombreSalaOption.IsSet)
                if (reserva.NombreSalaOption.Value != null)
                    writer.WriteString("nombreSala", reserva.NombreSala);
                else
                    writer.WriteNull("nombreSala");

            if (reserva.FechaReservaOption.IsSet)
                writer.WriteString("fechaReserva", reserva.FechaReservaOption.Value!.Value.ToString(FechaReservaFormat));

            if (reserva.HoraInicioOption.IsSet)
                writer.WriteString("horaInicio", reserva.HoraInicio);

            if (reserva.HoraFinOption.IsSet)
                writer.WriteString("horaFin", reserva.HoraFin);

            if (reserva.NombreResponsableOption.IsSet)
                if (reserva.NombreResponsableOption.Value != null)
                    writer.WriteString("nombreResponsable", reserva.NombreResponsable);
                else
                    writer.WriteNull("nombreResponsable");

            if (reserva.CantidadAsistentesOption.IsSet)
                writer.WriteNumber("cantidadAsistentes", reserva.CantidadAsistentesOption.Value!.Value);

            if (reserva.MotivoOption.IsSet)
                if (reserva.MotivoOption.Value != null)
                    writer.WriteString("motivo", reserva.Motivo);
                else
                    writer.WriteNull("motivo");

            if (reserva.EstadoOption.IsSet)
            {
                var estadoRawValue = EstadoReservaValueConverter.ToJsonValue(reserva.Estado!.Value);
                writer.WriteString("estado", estadoRawValue);
            }
        }
    }
}
