// <auto-generated>
/*
 * DemoApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using MiClienteReservas.Client;

namespace MiClienteReservas.Model
{
    /// <summary>
    /// ReservaListApiResponse
    /// </summary>
    public partial class ReservaListApiResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ReservaListApiResponse" /> class.
        /// </summary>
        /// <param name="isSuccess">isSuccess</param>
        /// <param name="message">message</param>
        /// <param name="data">data</param>
        /// <param name="errors">errors</param>
        [JsonConstructor]
        public ReservaListApiResponse(Option<bool?> isSuccess = default, Option<string?> message = default, Option<List<Reserva>?> data = default, Option<List<string>?> errors = default)
        {
            IsSuccessOption = isSuccess;
            MessageOption = message;
            DataOption = data;
            ErrorsOption = errors;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of IsSuccess
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> IsSuccessOption { get; private set; }

        /// <summary>
        /// Gets or Sets IsSuccess
        /// </summary>
        [JsonPropertyName("isSuccess")]
        public bool? IsSuccess { get { return this.IsSuccessOption.Value; } set { this.IsSuccessOption = new(value); } }

        /// <summary>
        /// Used to track the state of Message
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> MessageOption { get; private set; }

        /// <summary>
        /// Gets or Sets Message
        /// </summary>
        [JsonPropertyName("message")]
        public string? Message { get { return this.MessageOption.Value; } set { this.MessageOption = new(value); } }

        /// <summary>
        /// Used to track the state of Data
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<Reserva>?> DataOption { get; private set; }

        /// <summary>
        /// Gets or Sets Data
        /// </summary>
        [JsonPropertyName("data")]
        public List<Reserva>? Data { get { return this.DataOption.Value; } set { this.DataOption = new(value); } }

        /// <summary>
        /// Used to track the state of Errors
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<string>?> ErrorsOption { get; private set; }

        /// <summary>
        /// Gets or Sets Errors
        /// </summary>
        [JsonPropertyName("errors")]
        public List<string>? Errors { get { return this.ErrorsOption.Value; } set { this.ErrorsOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ReservaListApiResponse {\n");
            sb.Append("  IsSuccess: ").Append(IsSuccess).Append("\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("  Data: ").Append(Data).Append("\n");
            sb.Append("  Errors: ").Append(Errors).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ReservaListApiResponse" />
    /// </summary>
    public partial class ReservaListApiResponseJsonConverter : JsonConverter<ReservaListApiResponse>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="ReservaListApiResponseJsonConverter" /> class.
        /// </summary>
        public ReservaListApiResponseJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="ReservaListApiResponse" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ReservaListApiResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<bool?> isSuccess = default;
            Option<string?> message = default;
            Option<List<Reserva>?> data = default;
            Option<List<string>?> errors = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "isSuccess":
                            isSuccess = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "message":
                            message = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "data":
                            data = new Option<List<Reserva>?>(JsonSerializer.Deserialize<List<Reserva>>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "errors":
                            errors = new Option<List<string>?>(JsonSerializer.Deserialize<List<string>>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (isSuccess.IsSet && isSuccess.Value == null)
                throw new ArgumentNullException(nameof(isSuccess), "Property is not nullable for class ReservaListApiResponse.");

            return new ReservaListApiResponse(isSuccess, message, data, errors);
        }

        /// <summary>
        /// Serializes a <see cref="ReservaListApiResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="reservaListApiResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ReservaListApiResponse reservaListApiResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, reservaListApiResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ReservaListApiResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="reservaListApiResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ReservaListApiResponse reservaListApiResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            if (reservaListApiResponse.IsSuccessOption.IsSet)
                writer.WriteBoolean("isSuccess", reservaListApiResponse.IsSuccessOption.Value!.Value);

            if (reservaListApiResponse.MessageOption.IsSet)
                if (reservaListApiResponse.MessageOption.Value != null)
                    writer.WriteString("message", reservaListApiResponse.Message);
                else
                    writer.WriteNull("message");

            if (reservaListApiResponse.DataOption.IsSet)
                if (reservaListApiResponse.DataOption.Value != null)
                {
                    writer.WritePropertyName("data");
                    JsonSerializer.Serialize(writer, reservaListApiResponse.Data, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("data");
            if (reservaListApiResponse.ErrorsOption.IsSet)
                if (reservaListApiResponse.ErrorsOption.Value != null)
                {
                    writer.WritePropertyName("errors");
                    JsonSerializer.Serialize(writer, reservaListApiResponse.Errors, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("errors");
        }
    }
}
